### ISSUE TITLE
Non ascii characters in trigger name

### ISSUE THREAD

**Issue by aisbaa** [tyarkoni/transitions#104]
Hi, great library, thank you for sharing it with the rest of the world!

Its not a big issue but I'm wondering if it is possible to use `. , ( - %` symbols as triggers. If so how?
The reason I need this is that I'm using FSM for static code analysis, for example code below allows SQL injection:

```python
session.execute('select * from users where user.id = %s' % request.args['id'])
```

And it would be nice to trigger state transition using exact symbol without needing to translate it into symbol name, f.e:

```python
code_stmt.trigger('%')
```

**Comment by tyarkoni** [comment]
Not sure I understand the example... why would this present a problem from an injection standpoint? You can always sanitize the params in the request if you need to, no?

More generally, the issue I see here is that triggers need to be valid Python method names, since they get bound to the model. So I'm not sure how we could add special characters, since something like model.%my_trigger() isn't valid Python. (In theory we could add a Machine flag to prevent dynamic method binding, and then you could call the trigger directly, but that seems like an edge case, so I incline to not support it unless there's more demand.)

**Comment by aisbaa** [comment]
Yes your right, it is possible to sanitize arguments before interpolating those into string. But sometimes developer (including me) forget to do that. And I want to have static code analysis to detect that during automate testing stage.

**Comment by aleneum** [comment]
Hi @aisbaa,

what you describe is expected behaviour. Transitions binds events to model attributes with `setattr`. Since all object attribute and method names are more or less keys in the object's `__dict__` dictionary, every string which is a valid dictionary key should work with `getattr`. But as @tyarkoni mentions, you cannot call these functions directly because even though they are bound to the object they do not follow the python function naming scheme. 

If you do not mind the -- a bit indirect -- `getattr` approach, it should work just fine for your field of application.  A second approach would be to call the event trigger directly (for instance `machine.events['event_%'].trigger()`) as Tal suggests. This might be a bit more comprehensible.

You could extend your model like this to get your desired behaviour.
```python
class TestModel(object):
    def trigger(self, key):
        self.machine.events[key].trigger()
```

If using special characters cause problems elsewhere in transitions. Let us know.
