### ISSUE TITLE
GraphMachine does not include all edges in dot file

### ISSUE THREAD

**Issue by aisbaa** [tyarkoni/transitions#105]
I think I found a bug. Code below should produce graph with 4 directional edges, but it gets only one.

```python
from transitions.extensions import GraphMachine as Machine

class AToB(object):
    pass

transitions = [
    ['event_0', 'a', 'b'],
    ['event_1', 'a', 'b'],
    ['event_2', 'a', 'b'],
    ['event_3', 'a', 'b'],
]

machine = Machine(
    AToB(),
    states=['a', 'b'],
    transitions=transitions,
    initial='a',
    auto_transitions=False,
)

machine.graph.draw('/tmp/missing_edges.png', prog='dot')
```

transitions==0.4.0

**Comment by tyarkoni** [comment]
Thanks! I agree that we shouldn't just ignore the other transitions. But I'm not sure if we should add edges indefinitely in this scenario, as that could clutter things up quickly. The alternative would be to update the label of the existing edge (so it shows something like "event_0 | event_1 | event_2 | event_3". Could you add a figure showing what the updated result looks like when there are many other transitions? If it's still manageable, I'm happy to merge this. Otherwise maybe try the label updating route?

**Comment by aisbaa** [comment]
I don't mind, both approaches sound sensible.

with auto_transitions=False:
![big_no_auto](https://cloud.githubusercontent.com/assets/82692/15571879/6476caf6-2335-11e6-9593-d09aff42cdbc.png)

with auto_transitions=True:
![big_auto](https://cloud.githubusercontent.com/assets/82692/15571883/69029078-2335-11e6-868f-40be54e19d61.png)

Added a test and naive fix for this issue https://github.com/aisbaa/transitions/commit/de878bcc7fe76838bffa73849778772a9271d6d8 , will try to work on label approach in near future.

**Comment by aisbaa** [comment]
Hey, thank you guys! :smiley:

**Comment by aleneum** [comment]
thank YOU for revealing the issue and helping us to fix it 👍
