### ISSUE TITLE
Stack of state machines

### ISSUE THREAD

**Issue by imbaczek** [tyarkoni/transitions#131]
I'd like to reuse a state machine in different state machines, similarly to a subroutine call. This most likely means that machines should support stacking. Do you plan any support for such a feature?

The API could look somewhat like this:

```python
from common import send_email  # send email is a state machine definition

states = ['coffee', 'working', 'sending_email', 'done']
transitions = [
   ...
   {'trigger': 'send_email',  'source': 'working', 'dest': 'sending_email', 'push': {'target': send_email, 'initial': 'client_open', 'prefix': 'email'}},
   ...
]

employee = ...
m = Machine(model=employee, states=states, initial='coffee', ...)
employee.work() 
employee.send_email()  # push email controller
# employee.work()  # invalid
employee.email_compose()
employee.email_send()  # pops control back to the root state machine
# employee.email_send()  # invalid
employee.brew_coffee()
```

Maybe not the best example or the most elegant proposal, but the gist here is that I could reuse the send_email state machine code without it knowing that it's being reused. The real use case I have in mind involves controlling long running processes that have common parts, but an example would be very clunky.

 (I'll also readily admit that I haven't yet used the library, so please excuse any mistakes in the example above. I've grepped the source for 'push', though :) )

**Comment by aleneum** [comment]
transitions support hierarchical state machines which do support nesting of previously defined state machines. It is documented [here](https://github.com/tyarkoni/transitions#reuse-of-previously-created-hsms). This allows scenarios like this:

```python 
count_states = ['1', '2', '3', 'done']
counter = Machine(states=count_states, transitions=count_trans, initial='1') # hsm 1
...
states = ['waiting', 'collecting', {'name': 'counting', 'children': counter}]
collector = Machine(states=states, transitions=transitions, initial='waiting') # hsm 2
...
collector.state  # counting_2
```

Does this fit your needs or are you looking for something else?

**Comment by imbaczek** [comment]
After some playing around I think I could make it work, but it's not perfect. I've tried a different example:

```python
def make_reusable():
    states = ['init', 'using', 'done']
    transitions = [
        ['use', 'init', 'using'],
        ['done', '*', 'done']
    ]
    return Machine(states=states, transitions=transitions, initial='init')


def make_user():
    # you have to have a concrete machine instance to create a definition a dependent machine which looks wrong
    states = ['init', 'working', {'name': 'reusing', 'children': make_reusable()}, 'done']
    transitions = [
        ['work', 'init', 'working'],
        ['reuse', 'working', 'reusing_init'], 
        ['done', 'reusing_done', 'done']
    ]
    return Machine(states=states, transitions=transitions, initial='init')
    

user = make_user()
print(user.state)
user.work()
print(user.state)
user.reuse()
print(user.state)
user.use()
print(user.state)
user.done()
print(user.state) # reusing_done - expected
user.done()
print(user.state)  # somewhat unexpectedly: still reusing_done
```
This is an example of how a bug/misconstruction in the reusable state machine renders the parent crippled. This is a proposal I came up with that looks nearly like what I'd want:
```python
def make_reusable():
    states = ['init', 'using', PopState('done')]
    transitions = [
        ['use', 'init', 'using'],
        ['done', '*', 'done']
    ]
    return Machine(states=states, transitions=transitions, initial='init')


def make_user():
    reusable = make_reusable()
    states = ['init', 'working', PushState(name='reusing', target=reusable, initial='init'), 'done']
    transitions = [
        ['work', 'init', 'working'],
        ['reuse', 'working', 'reusing'], 
        ['done', 'reusing', 'done']
    ]
    return Machine(states=states, transitions=transitions, initial='init')
    

user = make_user()
print(user.state)
user.work()
print(user.state)  # working
print(len(user.stack))  # 1
user.reuse()
print(user.state)  # reusing
print(len(user.stack))  # 2
print(user.stack[-1].state)  # init
user.use()
print(user.state)  # reusing
print(len(user.stack))  # 2
print(user.stack[-1].state)  # using
user.done()
print(user.state)  # reusing
print(len(user.stack))  # 1
print(user.stack[-1].state)  # reusing - back to parent state because stack was popped
user.done()
print(user.state)  # done
```
I don't like how the machine reusable instance would have to use the parent's stack but maybe that's fine. Additionally you could have a 'target="self"' for a recursive state machine.

I think the single biggest reason I've got for push and pop is that I can just do
```python
from common import make_reusable
```
and not worry about state names changing in there as long as event names stay the same.

**Comment by aleneum** [comment]
> This is an example of how a bug/misconstruction in the reusable state machine renders the parent crippled.

The 'crippling' is a design choice which prefers event handling of children before parents.
Your `['done', '*', 'done']` is internally converted into `['done', '*', 'reuse.done']`.
This allows specialisation of generic 'meta' machines. If you want to alter the behaviour of the reused machine, I suggested using inheritance before nesting. 
A bottom-up (parent->children) approach also breaks the isolation of nested machines in a way that requires the user of a pre-defined machines to know quite some internals to not `interfere` with internal procedures.

For instance, wee use HSMs in robotics where generic searching procedures reuse control state machines for visual search (which themselves use machines for camera motor controls, computervision approaches and so on). A search pattern procedure triggering a `done` event meant for the internal machine which is 'catched' by the parent will cause undesired behaviour.

At some point you need some delegation for the stacking approach as well. If you are in a substate machine and a trigger is called which cannot be handled by the topmost machine like the event `work` in your example. Failing or throwing errors is not a good option though because from an external point of view `work` is a legit event but just unknown to the child. If your solution is delegating the event down the stack than this is practically what HSMs are already doing.

Long story short: This delegation is desired and required for complex HSM use cases.
If you want to prevent that, you can connect the nested state machine with custom mapping. The documentation mentions:
> Sometimes you want such an embedded state collection to 'return' which means after it is done it should exit...
```python
...
states = ['waiting', 'collecting', {'name': 'counting', 'children': counter, 'remap': {'done': 'waiting'}}]
```

`['done', '*', 'done']` would be internally converted (or actually partly kept) `['done', [all children states], 'done']`.

Thats pretty much your stack 'popping', isnt' it?

What we could add (again) is that if a machine defines an initial state it is also reused. This means if `reuse` is entered it will enter `reuse_init` automatically. 
This should be sufficient then:

```python
    states = ['init', 'working', {'name': 'reuse', 'children': reuse, 'remap': {'done': 'done'}}]
    transitions = [
        ['work', 'init', 'working'],
        ['reuse', 'working', 'reusing'], 
        ['done', 'reusing', 'done']
    ]
```

**Comment by imbaczek** [comment]
I think it would be mostly there, but I'm hitting this sanity check in nesting.py:227:

```python
            if s.name in duplicate_check:
                raise ValueError
```
(nb. it could use a message, I had to look up what's going on in the source)

With a stack or at least a prefix derived from the *child* machine instead of the parent I think it'd be fine.

**Comment by aleneum** [comment]
> (nb. it could use a message, I had to look up what's going on in the source)

Uh, sorry about that. Will be fixed asap.

> With a stack or at least a prefix derived from the child machine instead of/in addition to the parent I think it'd be fine.

That should happen already. Can you provide a small example which 'violates' the duplicate_check?

**Comment by imbaczek** [comment]
Just added what you recommended to the previous example:
```python
from transitions.extensions import HierarchicalMachine as Machine


def make_reusable():
    states = ['init', 'using', 'done']
    transitions = [
        ['use', 'init', 'using'],
        ['done', '*', 'done']
    ]
    return Machine(states=states, transitions=transitions, initial='init')


def make_user():
    # you have to have a concrete machine instance to create a definition a dependent machine which looks wrong
    states = ['init', 'working', {'name': 'reusing', 'children': make_reusable(), 'remap': {'done': 'done'}}, 'done']
    transitions = [
        ['work', 'init', 'working'],
        ['reuse', 'working', 'reusing_init'],
        ['done', 'reusing_done', 'done']
    ]
    return Machine(states=states, transitions=transitions, initial='init')


user = make_user()
print(user.state)
user.work()
print(user.state)
user.reuse()
print(user.state)
user.use()
print(user.state)
user.done()
print(user.state)
```
If I run this, I get a ValueError. Python 3.5.1, transitions 0.4.1. Renaming the parent's 'done' to 'done2' makes it run.

**Comment by aleneum** [comment]
This one seems to solved. If you discover further issues, feel free to reopen the issue.
