### ISSUE TITLE
Python 26 compability

### ISSUE THREAD

**Issue by luismartingil** [tyarkoni/transitions#157]
What Python structures are you using to not make this project Python26 compatible?

**Comment by aleneum** [comment]
Hello @luismartingil,

transitions relies on `collections.OrderedDict` for state management which has been introduced in Python 2.7. However, there is a backport of OrderedDicts (`ordereddict`). You would also need the backport modul `mock` and also `pycodestyle` and `six`.

The deal breaker in my oppinion is that we use `unittest` for testing which has been improved in 2.7. This means the tests written for transitions will not work for python 2.6 (I just tested that).
Unfortunately, I do not think we will support 2.6 since even the core development team of python discourages the use of 2.6 and earlier and I assume that some third party modules are not maintained for 2.6 as well.

I branched a version of transitions to an experimental [branch](https://github.com/tyarkoni/transitions/tree/deprecated-2.6) called deprecated-2.6. The imports seem to work and I fixed the obvious compatibility errors. But many tests fail due to syntax issues. You can give this a try and file pull requests in case you want to contribute to this branch.

Best regards,
Alex
