### ISSUE TITLE
Coroutine Support?

### ISSUE THREAD

**Issue by Kosyne** [tyarkoni/transitions#181]
Was wondering if support for coroutine callbacks / async stuff could be added, possibly via extension or such?

**Comment by aleneum** [comment]
Hello @Kosyne,

I am not aware of plans to support `asyncio` since we like to keep the backwards compatibility to python 2.7. `transitions` does support threading though. This allows wrapping `Machine` into `async` calls.

```python
import asyncio
from transitions.extensions.locking import LockedMachine as Machine
import time


async def do_this(model):
    model.running()
    print("I did this")
    model.done()
    return


async def do_that(model):
    model.running()
    print("I did that")
    model.done()
    return


def heavy_processing():
    time.sleep(1.0)

transitions = [
    {'trigger': 'running', 'source': 'Idle', 'dest': 'Running', 'after': heavy_processing},
    {'trigger': 'done', 'source': 'Running', 'dest': 'Idle'},
]

machine = Machine(states=['Idle', 'Running'], transitions=transitions, initial='Idle')
loop = asyncio.get_event_loop()

print("Doing things...")
loop.run_until_complete(asyncio.gather(
    do_this(machine),
    do_that(machine)
))
loop.close()
```

It may be possible to extend `LockedMachine` to support asyncio directly. If you have any suggestions, let me know.

**Comment by oz123** [comment]
@aleneum it is possible to use trollius  for having asynio with Python 2.7.

https://pypi.python.org/pypi/trollius

**Comment by aleneum** [comment]
Hello @oz123,

> is possible to use trollius for having asynio with Python 2.7 

I have seen this working for the `autobahn` project. So yeah, probably.

I wrote a small test for this and think the question *What* should be called asynchronously has to be clarified in advance:

* Case A: `Even.trigger` (the methods which will be bound to the models)

This is the easiest case which can be achieved by adding a method to a model definition, such as:

```python
import asyncio
from transitions.extensions.locking import LockedMachine as Machine


class Model(object):

    async def run_threaded(self, method, *args, **kwargs):
        await asyncio.coroutine(getattr(self, method))(*args, **kwargs)

    def report(self, task):
        print('Done with %s' % task)
        self.done()


transitions = [
    {'trigger': 'run', 'source': 'Idle', 'dest': 'Running', 'after': 'report'},
    {'trigger': 'done', 'source': 'Running', 'dest': 'Idle'},
]

model = Model()
machine = Machine(model=model, states=['Idle', 'Running'], transitions=transitions, initial='Idle', queued=True)

print("Doing things...")
loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.gather(
    model.run_threaded('run', task='task A'),
    model.run_threaded('run', task='task B')
))
loop.close()
```
This is just one way to solve it. You can probably encapsulate async even further but unfortunately it cannot be integrated into `Event.trigger` that easily because this messes with the order of transitions when a trigger is called within a callback.

* Case B: `Model.callbacks` (like `prepare`, `before`, `after`)

This is where things start to get complicated because who should `await` what? Should `check/before/after` called parallel or sequential? And how do we maintain the order of certain processes if the event loop is already used for executing the event trigger?

Feedback welcome.

**Comment by aleneum** [comment]
Just a minor remark: case A is enough to process events asynchronously. I use Robotic Service Bus ([RSB](https://code.cor-lab.de/projects/rsb)) to dispatch asynchronous events with a similar method (see [rsbhsm](https://github.com/aleneum/rsbhsm)).

RSB uses PubSub Event handler. I added an `onMsg` function to my custom `RSBEvent` which is called when a message is received. This way I can still call `Event.trigger` synchronised. `activate` and `deactivate` is just some convenience listener management and not required for using transitions to handle events.

**Comment by aleneum** [comment]
I guess I found a way to achieve things like this

```python
class Model():
    ...
    def callback1(): ...
    def callback2(): ...
    ...
loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.gather(
    model.run(task='task A'),
    model.run(task='task B')
))
loop.close()
```
without the need of extra work in the model. This means events can be handled asynchronously. The drawback is, that all model callbacks have to be synchronous and I guess that's not what you (@Kosyne) require, right?

I guess what you need is:

```python

class Model():
    async def callbackA(): ...
    async def callbackB(): ...

model.run(..)
```

correct? Could you provide a minimal example of what you trying to achieve?

**Comment by Kosyne** [comment]
@aleneum Yeah, that bits a no-go. I could actually probably get by with the reverse, lol (events sync, callbacks async) . I'm writing a discord bot using [discord.py](https://github.com/Rapptz/discord.py) for python 3.4+, and I need practically every callback to be called asynchronously, as discord.py's API is full of coroutines.

The exact case is making a state-based jukebox for the bot (playing/paused/idle/etc), and I want each of the callbacks to be able to be awaited/yielded from.

I hacked together the jankiest (but somehow still functional) version of this by 'async def'/'await'-ing anything relating to the callbacks and triggers in 'transitions/core.py', hah. That resulted in both events and callbacks being async, and thus needing to be 'await'ed, which my desired behavior. I haven't encountered anything screwy yet, but I'll definitely look into some of the above methods though, because I really don't like the idea of having to maintain my own hacked-up version of this alongside my other projects.

(And sorry for late reply, github alerts me for all sorts of things... but not this thread. Go figure)

**Comment by aleneum** [comment]
Hi @Kosyne,

I had a brief look at discord.py and I would agree that it seems like you need async for events (to handle discord events) and callbacks (for sending messages etc.). The danger of asynchronous event handling lies in parallel execution. What happens when you receive an `on_message` event while another one has not been completely processed yet? `core.Machine` is not threadsafe which means you are at a risk to face racing conditions and/or weird behaviour when this happens (also debugging will be pure pain).
I recommend using `LockedMachine` since this will make sure that events will be handled synchronised. 
However, you still have to make sure that `Event.trigger` does not return before the event and its callbacks have been processed completely. Otherwise the lock may be released too early.

**Comment by Kosyne** [comment]
The triggers are setup to be async as well, and I have each command (from the on_message event) put into a queue where each trigger is awaited, so it does not continue until the trigger in question is fully resolved. Thus far, I haven't ran into such issues, but I'll definitely be keeping an eye out for them in case, and will also be giving `LockedMachine` a try. Hopefully though, sometime in the future, maybe we could see a (very much optional) extension for something like an `AsyncMachine` :)

**Comment by aleneum** [comment]
Hi @Kosyne,

> Hopefully though, sometime in the future, maybe we could see a (very much optional) extension for something like an AsyncMachine :)

sure thing. Personally, I have limited experience with asyncio but if you propose a maintainable extension based on your experience and open a pull request, I would gladly review it.

For now I close this issue. Feel free to reopen it, if you want to discuss this matter further.

Good luck with your bot!

**Comment by ivanteresh** [comment]
Hello, @aleneum.
I'm currently working on a project based on the principle of chat-bot. In it, I use pytransitions to handle the current state of the bot dialog with the user. To support the asynchronous processing mode, I wrote my own extension for a state machine. In it, I was able to create an event trigger, all callbacks and even status checks are asynchronous. The order of the callbacks is saved and works as expected. What do you think about if I send you a pull-request for review?

**Comment by aleneum** [comment]
Hello @ivanteresh,

sounds great. If you open a pull request I will gladly have a look at it.

**Comment by lromor** [comment]
Hello,
what about running the state machine in a python thread and schedule the coroutines from there using

future = asyncio.run_coroutine_threadsafe(my_transition_callback(), loop)
result = future.result(timeout)  # Wait for the result with a timeout

?

**Comment by lromor** [comment]
+1 for this feature

**Comment by lucalenardi** [comment]
+1 for `async.io` support.
