### ISSUE TITLE
setting state of a Machine instance

### ISSUE THREAD

**Issue by oz123** [tyarkoni/transitions#185]
Hi,
I am a new use of this great library. I was quite surprised to find out that I can do the following:

```
In [2]: class Matter(object):
   ...:     pass
   ...: 
   ...: lump = Matter()
   ...: 

In [3]: from transitions import Machine
   ...: machine = Machine(model=lump, states=['solid', 'liquid', 'ga
   ...: s', 'plasma'], initial='solid')
   ...: 

In [4]: lump.state = "eggs"

In [5]: lump.state
Out[5]: 'eggs'
```

This should not be allowed if the state is not defined.

This behaves as I expected:

```
In [11]: machine.set_state("eggs")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-f147b82fa5fb> in <module>()
----> 1 machine.set_state("eggs")

/home/oznt/.virtualenvs/hagenv2/lib/python3.5/site-packages/transitions/core.py in set_state(self, state, model)
    454         """ Set the current state. """
    455         if isinstance(state, string_types):
--> 456             state = self.get_state(state)
    457         models = self.models if model is None else listify(model)
    458         for m in models:

/home/oznt/.virtualenvs/hagenv2/lib/python3.5/site-packages/transitions/core.py in get_state(self, state)
    448         """ Return the State instance with the passed name. """
    449         if state not in self.states:
--> 450             raise ValueError("State '%s' is not a registered state." % state)
    451         return self.states[state]
    452 

ValueError: State 'eggs' is not a registered state.
```

IMHO, it should not be hard to implement a fix to that, by turning the attribute state to a property. Will you merge such a PR if I implement it?

Thanks!

**Comment by aleneum** [comment]
Hello @oz123,

I also assume it would be possible to safeguard `Model.state` somehow but I am not sure handling this case is sending the right message. First, `state` should be considered `read-only` and therefore should only be altered by a machine. However, this is more a suggestion than a strict rule since: second, `state` is a property of the model which in my oppinion makes fiddling with `Model.state` a responsibility of the model. Third, binding `Model.state` to a machine instance (which would be required to check if a state is valid) removes the ability to use one model with multiple machines. Since `Machine.set_state` already offers the feature to directly set the state of models, safeguarding `Model.state` sure improves convenience but does not offer new functionality.

This is only my 2 cents and I am open for suggestions why this safeguarding is a valuable addition to the library. If others vote for this feature I will change my mind too. 

This being said, you can achieve your desired behaviour quite easily by defining `Model.state` yourself:

```python
from transitions import Machine


class Model:

    def __init__(self, *args, **kwargs):
        self._state = None
        # to circumvent bootstrapping we intialize the machine without a model.
        self.machine = Machine(model=None, *args, **kwargs, add_self=False)
        self.machine.add_model(self)

    @property
    def state(self):
        return self._state

    @state.setter
    def state(self, value):
        if value in self.machine.states:
            self._state = value
        else:
            raise ValueError("State '%s' not defined" % value)


model = Model(states=['A', 'B'], transitions=[['go', 'A', 'B']], initial='A')
print(model.state)
model.go()
print(model.state)
model.state = 'A'
print(model.state)
try:
    model.state = 'egg'
except ValueError as e:
    print(e)

```

Best regards!

**Comment by oz123** [comment]
The is indeed very smart way of doing that! Maybe we should just this to the documentation, and avoid messing around with the Machine class.

**Comment by aleneum** [comment]
I am glad that this fits your needs.

I will close this issue for now but feel free to reopen it if you consider this to be still an issue. 
This matter is not really a feature of `transitions` but rather a way of application. So having this here (or Stackoverflow) should be sufficient for people to stumble upon. If a similar issue is opened again, we should consider to mention this in the documentation though.
