### ISSUE TITLE
LockedMachine callback will not fire

### ISSUE THREAD

**Issue by kr2** [tyarkoni/transitions#214]
I think 4. should work since 3. does.

```python
from transitions import Machine, LockedMachine 
```

## 1. OK:
```python
class Matter(object):
    def on_enter_A(self): print("We've just entered state A!")

lump = Matter()
machine = Machine(lump, states=['A', 'B', 'C'])
lump.to_A()
```

We've just entered state A!

True

## 2. OK:
```python
class Matter(Machine):
    def on_enter_A(self): print("We've just entered state A!")
    def __init__(self):
        super(Matter, self).__init__(self, states=['A', 'B', 'C'])  

lump = Matter()
lump.to_A()
```
 We've just entered state A!

True

## 3. OK:
```python
class Matter(object):
    def on_enter_A(self): print("We've just entered state A!")

lump = Matter()
machine = LockedMachine (lump, states=['A', 'B', 'C'])
lump.to_A()
```
We've just entered state A!

True

## 4. Fail. Missing print output:
```python
class Matter(LockedMachine ):
    def on_enter_A(self): print("We've just entered state A!")
    def __init__(self):
        super(Matter, self).__init__(self, states=['A', 'B', 'C'])
        

lump = Matter()
lump.to_A()
```

True

**Comment by aleneum** [comment]
This is a tricky one since `LockedMachine` wraps instance methods in partials. To determine if a function should be used as a callback, we check if the returned callable is a method (bound to a model instance). We cannot just check if the returned function is callable since "Machine.on_enter_<state>" also returns a partial (a wrapped call to add_callback). 
Small example:

Case A (Model != Machine):
model.on_enter_A -> method
model.on_enter_B -> undefined

Case B (Model == Machine):
model.on_enter_A -> method
model.on_enter_B -> partial

Case C (Model == LockedMachine):
model.on_enter_A -> partial (from the `Model` part)
model.on_enter_B -> partial (from the `Machine` part)

**Solution**
This special case will now be handled in `LockedMachine`.  Thank you for the bug report!
