### ISSUE TITLE
callback not working when using alternative initialisation pattern 1

### ISSUE THREAD

**Issue by bit-pirate** [tyarkoni/transitions#24]
I implemented a simple SM using the first pattern described in the [alternative initialization patterns](https://github.com/tyarkoni/transitions#alternative-initialization-patterns). Unfortunately, I cannot get the callbacks to work (e.g. `on_enter_<some_state>`). I prepared a working and a not working example.

_alternative initialisation pattern 1 (not working)_

`test.py`:
```
#!/usr/bin/env python

from transitions import Machine, State


def test_callback():
    print 'testing callbacks'

if __name__ == '__main__':

    states = ['StateA',
              State(name='StateB', on_enter=['test_callback'])]
    transitions = [{ 'trigger': 'triggerA', 'source': 'StateA', 'dest': 'StateB' }]
    sm = Machine(states=states, transitions=transitions, initial='StateA')

    print sm.state

    sm.triggerA()

    print sm.state
```

console output:
```
$ ./test.py 
StateA
Traceback (most recent call last):
  File "./test.py", line 18, in <module>
    sm.triggerA()
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 214, in trigger
    if t.execute(event):
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 134, in execute
    machine.get_state(self.dest).enter(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 48, in enter
    getattr(event_data.model, oe), event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 447, in callback
    func(*event_data.args, **event_data.kwargs)
TypeError: 'NoneType' object is not callable
```

_normal/default initialisation (working)_

`test2.py`:
```
#!/usr/bin/env python

from transitions import Machine, State

class TestModel(object):
    def test_callback(self):
        print 'testing callbacks'

if __name__ == '__main__':

    test_model = TestModel()

    states = ['StateA',
              State(name='StateB', on_enter=['test_callback'])]
    transitions = [{ 'trigger': 'triggerA', 'source': 'StateA', 'dest': 'StateB' }]
    sm = Machine(test_model, states=states, transitions=transitions, initial='StateA')

    print test_model.state

    test_model.triggerA()

    print test_model.state
```
console output:
```
$ ./test2.py 
StateA
testing callbacks
StateB
```

Am I missing something or doing something wrong here?

PS: Alternative initialisation pattern 2 works as well.

**Comment by tyarkoni** [comment]
Hi @bit-pirate, thanks for using the package!

As currently implemented, all callbacks are assumed to be located in the model class rather than in the global environment. That's still true when you initialize the Machine with itself as the model. In your example above, you're defining test_callback() outside of the Machine, so when it looks for the callback function at self.test_feedback, it can't find it. But you can fix this by attaching your method to the machine instance:

```
from transitions import Machine, State


def test_callback():
    print 'testing callbacks'

if __name__ == '__main__':

    states = ['StateA', State(name='StateB', on_enter=['test_callback'])]
    transitions = [{ 'trigger': 'triggerA', 'source': 'StateA', 'dest': 'StateB' }]
    sm = Machine(states=states, transitions=transitions, initial='StateA')
    sm.test_callback = test_callback
```

In theory I suppose we could inspect all functions currently in scope for a match to the callback... but that seems dangerous. In general I recommend going with the second approach (i.e., inheriting from Machine) for precisely this reason--it lets you contain all model logic in a separate class rather than monkey-patching the Machine class or adding to it at runtime.

I'm closing this, but feel free to re-open it if needed.

**Comment by bit-pirate** [comment]
I'm fine with leaving it as is following your suggestion. Though it would be good to add this solution as a note to the alternative initialisation section in the readme.
