### ISSUE TITLE
Using Machine(s) as State(s)

### ISSUE THREAD

**Issue by renatosamperio** [tyarkoni/transitions#31]
Can I use composite states like a state? Like using another state machine as a state?

**Comment by tyarkoni** [comment]
There's currently no support for compositing or hierarchical/nested states. I think some rudimentary support for hierarchical states could be added fairly easily, but I don't have the time to do it myself at the moment. If you (or anyone else) are interested in working up a PR, I can make some suggestions.

That said, I'll also give my standard caveat, which is that I don't like to add major new features unless multiple users express desire for them, because there are a lot of potential extensions to a package like this, and I want to avoid bloat. So if anyone else wants to weigh in, please do.

**Comment by tyarkoni** [comment]
Closing this for the time being; can be re-opened if necessary.
