### ISSUE TITLE
Looping / "Running" a Machine

### ISSUE THREAD

**Issue by kmcnayr** [tyarkoni/transitions#36]
I might be missing a critical concept; I can't find any examples or snippets that show how to do this:

How would I setup a machine to move to the next state until an end state is reached? All of the examples show manual steps from one state to the next. I'd like to "start" the machine and have it automatically transition from one state to the next using conditional transitions until it reaches the "end" state.

Any suggestions are much appreciated. I'm really interested in using this library; it seems to be very clean and lightweight compared to other python implementations of FSM.

**Comment by wtgee** [comment]
I end up rolling my own, which is straightforward. You just basically throw things in a while loop and then check the state status.

Example [here](https://github.com/panoptes/POCS/blob/develop/panoptes/state_machine/transitions_fsm.py#L80)

I essentially use `transitions.Machine` as base class and create my own state machine. In addition to an `initial` state, the state machine itself keeps tracking of the previous and the next state. If the `next_state` is set to 'exit' I do just that. Note that my machine doesn't have a static route through the machine but does have a static exit point. My state machine class is responsible for setting things up as well as defining `enter_state` and `exit_state` methods that are called before and after each state as well an `execute` method that calls the same method name in per state.

**Comment by tyarkoni** [comment]
This issue has come up several times in various flavors; see for instance #18 and #30. As @wtgee points out (thanks!), if all you need to do is just keep the main thread running, you can embed your code in a while loop and just try to advance state every iteration. As long as you give your transitions the same trigger name, they will be executed serially until one passes (see the README), so you can avoid embedding transition logic inside the callbacks. Generically, you could be looking at something as simple as:

```python
while True:
    if model.is_finished():
        break
    model.next_state()
```

You can then use the on_enter, on_exit, before, and after callbacks (attached to States and Transitions, respectively) to push a lot of your code into the model rather than checking a lot of conditionals inside the while loop.

Hope this (and @wtgee's code sample) helps!

**Comment by kmcnayr** [comment]
This is perfect and is along the lines of what I was thinking the answer might be. Thanks a bunch!!
