### ISSUE TITLE
States that triggered event

### ISSUE THREAD

**Issue by omago** [tyarkoni/transitions#37]
Hi, 

I have a question. I have a code like this

            {'trigger': 'new_to_pending', 'source': States.NEW, 'dest': States.PENDING,
             'before': 'write_insert_statement',
             'after': ['save_current_state',
                       'set_related_active_instructions_to_pending_state']},

i write_insert_statement i would like to access source and dest states, if i send send_event=True to initializer i get event_data object but his object only contains initial state. Is it possible to retrieve both states source and dest?

Best,
Domagoj

**Comment by wtgee** [comment]
I know you have access to the name of the state via the transition event:

dest_state = event_data.event.name.replace('to_', '')
prev_state = event_data.state.name

But since you haven't gone to the dest_state yet my feeling is that there
is no object to have. You have the transition object and the previous state
object. The transition object indicates what the dest_state will be.

Hope that helps.

~Wilfred

On Tue, Nov 10, 2015 at 4:18 AM, omago <notifications@github.com> wrote:

> Hi,
>
> I have a question. I have a code like this
>
>         {'trigger': 'new_to_pending', 'source': States.NEW, 'dest': States.PENDING,
>          'before': 'write_insert_statement',
>          'after': ['save_current_state',
>                    'set_related_active_instructions_to_pending_state']},
>
> i write_insert_statement i would like to access source and dest states, if
> i send send_event=True to initializer i get event_data object but his
> object only contains initial state. Is it possible to retrieve both states
> source and dest?
>
> Best,
> Domagoj
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tyarkoni/transitions/issues/37>.
>



-- 
~Wilfred Tyler Gee

**Comment by omago** [comment]
Thanks Wilfred,

In the meantime i also noticed event.name so i think i will use it.

**Comment by tyarkoni** [comment]
I added a transition pointer to EventData objects for convenience, so you can now do event_data.transition.dest.

**Comment by omago** [comment]
Thanks!
