### ISSUE TITLE
Before and after state change

### ISSUE THREAD

**Issue by omago** [tyarkoni/transitions#40]
Hi everybody,

I noticed one thing, "condition" callback is triggered before "before" callback. I expected that "before" is called before "condition"? Does my logic make any sense?

**Comment by tyarkoni** [comment]
The issue here is that people can reasonably have different expectations about what should happen if a condition fails. One view is that a "before" callback should always run, even if the transition never completes successfully (because a condition fails). The counterargument is that you might not want before callbacks to fire at all if you know the transition won't happen, because it could leave you in an internally inconsistent state. For a lightweight package like this, my sense is that the latter case is probably the behavior most users expect. So I implemented it with condition-checking first, to prevent any further logic in the event the transition is invalidated.

I'd be happy to change the order if there's general agreement that that's preferable, but I worry that that would introduce undesirable behavior in other respects. An unambiguous way to resolve this would be to split the before callback into two separate callbacks (e.g., 'before' and 'around'), but I'm kind of hesitant to keep adding callbacks as my overriding concern is to keep it simple.

Labeling this as a question so other people can weigh in.

**Comment by omago** [comment]
Thanks for the reply. My view is that before callback is some kind of preparation stage for the transition, as such my view is that it need to be triggered always. After before "condition" is triggered and "condition "is the one that decides about successful transition. After that "after" callback is triggered. Also it would be cool to have two after callback, after_success, after_fail - something like that.

**Comment by tyarkoni** [comment]
That's reasonable. I'll leave this open for further comment, and if there's enough sentiment in favor of always firing "before" events, we can do it that way in a future release.

**Comment by harshitjain-cs** [comment]
Is there any way to pass data along with defining conditions that use that data, in a single transition?

**Comment by harshi3t** [comment]
Is there any way to pass data along with defining conditions using the same data, in a single transition?
something like : 
`machine.add_transition('trigger', 'stateA', 'stateB', before=['set_environment', 'fn1'], conditions=['cond1'])`
Here fn1 and cond1 use the data passed through trigger

**Comment by tyarkoni** [comment]
Yes, conditions and before/after callbacks all receive EventData just like other callbacks. See the "Passing Data" section in the README. If it doesn't work as described, open a new issue.

**Comment by aleneum** [comment]
Hi,

I do not want to judge who is right or wrong here but for me "before" refers to the transition which is about to occur rather than the check if the transition should occur or not. I am pretty sure that there are cases where you prefer to reuse the preparation of the check but the same is true for (certain) transitions. 

I am biased towards tyarkoni's point of view because if "before" refers to the check preparation, we loose the ability to do something -- independently of the state -- before the transition occurs since we have to rely on exit and enter functions of (maybe multiple) states then.

So I would recommend to call a preparation function from within the condition check if necessary and also a "tear down" function if the transition wont happen. This is most likely two extra lines of code and should also be easy to comprehend.

Best regards,
Alex

**Comment by tyarkoni** [comment]
Thanks for the feedback, @aleneum. Will keep this open for further input.

**Comment by omago** [comment]
I think @aleneum did not understand my point. 

My point was that "condition" is triggered before "before" and i would expect that "before" is triggered before "condition". In this situation where "condition" is triggered before "before" and "after" i am not sure what is the difference between "before" and "after" - both are always triggered.

**Comment by aleneum** [comment]
Hi @omago,

I guess I understand your point. And I also see where such a solution comes in handy (e.g. flushing a buffer, synchronizing resources, query things...). Let me try to clarify why I personally favour the current concept:

Right now the execution order is `condition -> before -> transition -> after` (case A). Conceptual speaking, `before` refers to a certain transition.
You argue for a concept change to `before -> condition -> transition -> after` (case B) where `before` references  the condition check(semantically). And you ask "Why do both functions refer to transition? What must be done in `before` that cannot be done in `after`" (right?).
The interesting part of `before` and `after` is, that both are independent of the targeted state which means I do not have to couple transition related logic to state related logic. That means I can use them to wrap the transition without touching the target state. Same pattern can be found elsewhere, sometimes called setup/prepare and tearDown/cleanUp (e.g. unit tests).

So you ask where setup/tearDown could be useful:
Let's say I have a resource which must not be accessed during state transition (the current state for instance; it's undefined during transition but not during condition check). This means I have to lock and unlock the resource somehow during transition.

Let's say we have:

```python
def beforeCheck(): #always called
  ...
def afterCheck(): #not specifically mentioned but probably a case for someone somewhere
  ...
def check(): #always called
  ...
def beforeTransition(): #only called if transition happens
  res.lock();
def afterTransition(): #only called if transition happens
  res.unlock();
``` 

In case A I can put `beforeCheck` and `afterCheck` at the beginning and end of `check` to achieve your desired behaviour. This will keep everything condition related in one spot.
```python
def check():
  beforeCheck(); # these are the two lines 
  #do stuff
  afterCheck(); # I was talking about earlier
  return result;
```
The assignment is `condition=check, before=beforeTransition, after=afterTransition`.

In case B I would assign `before=beforeCheck, condition=check, after=afterTransition`. 
Now I have to handle a fulfilled condition myself _within_ `check` or in the `enter` function of the target state since somewhere I have to lock/assign/handle the resource. And without `before=beforeTransition` I cannot do that after the condition check is done. In my eyes the cleanest solution for such a case would be:
```python
def check():
  ...
  if result is True:
    beforeTransition();
  return result;
```

So, it is possible but it mixes two things: condition checking and transition preparation. Having `before` as `beforeCheck` and `after` as `afterTransition`also breaks the setup/tearDown pattern which in my eyes is often pretty handy. It might be useful to think about a similar thing for condition checking instead. So instead of `before` and `after` one could argue for `beforeCondition`, `afterCondition`,`beforeTransition` and `afterTransition`. This might clarify what is executed when. I, however can live with the two extra lines of code in the condition check in case A though. But that is just my opinion :).

Sorry for the long post.

**Comment by TheMysteriousX** [comment]
I had a similar requirement for running code on transitions before conditions were checked - I initially did it like this:

```python
def condition():
  action();
  return real_condition();
```

But if only some transitions have conditions, you either:
* swap between the above and the `before` callback
* write a dummy condition that is always true

Neither is great for consistency/clarity/maintainability or making code written by users of the library easy to follow.

I've tidied it up and pushed it to my fork here: https://github.com/TheMysteriousX/transitions/commit/15a683b79610cfdde68a1bcf6770fb646e46f061

I can send it as a pull request, if desired. Happy to make changes too.

**Comment by aleneum** [comment]
I think this 'prepare condition' thing is quite complex. I can think of at least two different scenarios:
* prepare -> check -> tearDown -> prepare -> check -> tearDown
* prepare -> check -> check -> tearDown

And what if some conditions require preparation and others don't...

But that is more complex than what you have in mind. So just for clarification: you argue for an `action` keyword which always executes code when `Event.trigger` is called?

My first thought was 'well, if it is always called, then call it':
```python
# action keyword
transitions=[
    {'trigger': 'maybe_go_B','source':'A', 'dst':'B', 'action':'action', 'conditions':['testA,testB']},
    {'trigger': 'maybe_go_C_else_D','source':'A', 'dst':'C', 'action':'action', 'conditions':'testC'},
    {'trigger': 'maybe_go_C_else_D','source':'A', 'dst':'D', 'action':'action'}
]
# explicit call
model.action()
model.maybe_go_B()
...
model.action()
model.maybe_go_C_else_D()
```

I don't quite get yet why `action` is more comprehensible than an explicit call.

**Comment by TheMysteriousX** [comment]
Sorry, I omitted that from my post; that `action` only executes if the transition is valid is a critical point.

For a concrete example, I have a command parser, where each commend is a transition. A command comes in, and it is mapped to a transition. If the transition is valid in the current state, then action fires updates the model according to what the command does.

There then may or may not be a condition to verify the models state (did the user send us enough information, did they send junk...) before actions fire to cleanup the previous state, and enter the new state.

This can all be done without adding an additional callback with workarounds as detailed, but the clarity is much higher and there's no possibility that someone will try and "fix that condition that's always true".

**Comment by tyarkoni** [comment]
Okay, I think I'm sold on adding another callback, since it's come up a couple of times now. I think your implementation looks good, @TheMysteriousX. The only thing I'm not sure about is the name... I find 'action' kind of ambiguous. I think if we replace 'before' with 'before_check' and 'before_transition' (while keeping 'after'), that seems clearer. For backward compatibility, we could also alias 'before' to 'before_transition'--at least for the next few releases (the docs wouldn't mention it, and we could remove it at some point).

Thoughts, @aleneum, @wtgee?

**Comment by aleneum** [comment]
Yeah, I am also convinced that this is a useful addition. Concerning naming: I think `before_transition`/`before_check` is a good solution. It might raise questions why there is no `after_check` and `after_transition` though. `action` is a bit more generic which is good (not focused on check) but also bad (semantically not as well embedded in the execution timeline as `before_check`). From these two I'd go with `before_*` and let time decide if we have to think about proper `after_*` handling. 
A third option could be thinking in events and let the keyword reference the transition. In this case I'd name it `on_triggered`, `on_executed` (`before_execute`?) or similar.

**Comment by omago** [comment]
Hi tyarkoni, what about this? Also it would be cool to have two after callbacks, "success", "fail".

**Comment by TheMysteriousX** [comment]
I've no particular attachment to `action`; from the other suggestions I think either is fine as long as it's consistent with the rest of the callbacks, so I think changing the names of the other callbacks and aliasing the old ones might be sensible.
