### ISSUE TITLE
More powerful transiton?

### ISSUE THREAD

**Issue by ExpandOcean** [tyarkoni/transitions#5]
I found it may be difficult to pass data from trigger to transition's condition. For example, trigger=foo,when bar>5, StateA->StateB,  I can't use Machine.foo(bar=6) to excute the transition.

By the way, I think a transition including **Event Trigger**, **Condition**, **Condition Action**, **Transition Action**  is necessary for building compicated FSM. 
That kind of  transition is described in http://mathworks.com/help/stateflow/ug/transitions.html

**Comment by tyarkoni** [comment]
Can you paste a code snippet that doesn't work, for your data-passing example? Depending on how you've set it up, you may need to set send_event=True in the initializer (see the README), but it should work.

Regarding the MathWorks example, you can duplicate most (though not quite all) of that functionality with the existing code in transitions... callbacks can be added to both states and transitions (i.e., states have 'on_enter' and 'on_exit' callbacks, and transitions have 'before' and 'after' callbacks), and transitions can have a list of conditions attached that must evaluate to True in order to execute. As far as I can see, the only difference in the MathWorks implementation is that one can have code that executes on successful condition evaluation even though the transition destination is not known to be valid yet. I need to think some more about whether that's worth implementing here, but I guess my first impression is that it doesn't seem like a very common use case.

**Comment by ExpandOcean** [comment]
When I set send_event=True, it works:) Another question, how can I add some logical operation(AND/OR/NOT) to conditions. I have no idea how to excute the transition when condistion is **not** true. I think define a not_condition function should work, but it seems a little ugly. Thank you!

**Comment by tyarkoni** [comment]
I added an 'unless' argument in 67dce5d8d5123d6317816227c06b4d9e818198b6. It behaves just like conditions, except inverted (i.e., all conditions in the unless list must return False, or the transition fails). I think adding logic to handle disjunctions is probably not worth the extra code; I don't think that's a very common use case. But if other people request OR handling, we can always revisit this.
