### ISSUE TITLE
plotting graphs

### ISSUE THREAD

**Issue by stvo1** [tyarkoni/transitions#57]
I tried the following code to verify that I have a correct state machine :

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-

from fileStateMachine import *
states = ['1', '2', '3']
transitions = [
    {
        'trigger': 'advance',
        'source': '1',
        'dest': '2',
        'conditions': 'valid_data'
        },
    {
        'trigger': 'advance',
        'source': '1',
        'dest': '3',
        'unless': 'valid_data'
        }
]

class MF():
	def valid_data():
		return random.randrange(100) < 50

lump = MF( )

# the actual state machine a file posses.
machine = Machine( lump, states=states, initial='1', transitions=transitions, auto_transitions=False )

#print state machine
graph = None
try:
	graph = machine.get_graph()
except :
	printError('pygraphviz is missing.')
	sys.exit(101)
graph.draw('my_state_diagram.png', prog='dot')
print 'TODO'
```
which result in the following state diagram:

![my_state_diagram](https://cloud.githubusercontent.com/assets/6562736/12146087/16520f64-b492-11e5-8741-abb9aa2d7ac6.png)

now a bunch of questions arise:
1) Is there a concept to tell a/multiple State(s) that it is final or has a final property.
2) Can we pass this state to pygraphviz.
2) Why is the initial state ignored in the graph, or is it ignored in the machine as well? 
3) Would it be possible to add the condition to the graph, e.g. as an argument to advance -> "advance( valid_data==true )", since IMHO this small state machine is valid.

Many thanks in advance
stvo

**Comment by tyarkoni** [comment]
Hi @stvo,

The graphing functionality (which @svdgraaf was kind enough to contribute) is pretty basic, so there's minimal support for different plotting options. To answer your questions in order:

1) Not at the moment.
2) No, because of (1).
3) Not sure I follow... you define the initial state as '1', and it looks like that is indeed the initial state in the graph (with the double circle). I don't get the 'new' state in my graph for your code; are you using an up-to-date version? However, I do see a separate problem--and maybe this is what you're getting at--which is that the second transition (from 1 --> 3) appears to be ignored. This would be a bug, and I'm guessing it has something to do with the fact that the transitions have the same named trigger. Can you open a separate issue just for this, if you agree that this shouldn't be happening?
4) I probably won't be able to do this any time soon myself, but if you open a separate issue for it with a clear example of the use case, I'll mark it as a enhancement and hopefully someone can add it.

Note that the get_graph() call returns a pygraphviz AGraph object, which has all of the usual properties. So you could potentially modify the node/edge properties directly, in lieu of an option to do it in transitions.

Hope that helps! I'll close this issue, but feel free to open new ones for more specific bugs/requests per the above.
