### ISSUE TITLE
Wildcard transitions are not applied on newer states

### ISSUE THREAD

**Issue by GertBurger** [tyarkoni/transitions#65]
If one adds a state after a transition with a wildcard source then that transition will not apply on the new state.

```
In [6]: m=transitions.Machine()

In [7]: m.add_transition('one', '*', 'final')

In [8]: m.add_transition('two', 'initial', 'two')

In [9]: m.states
Out[9]: OrderedDict([('initial', <transitions.core.State object at 0x10c84dcd0>)])

In [10]: m.events
Out[10]:
{'one': <transitions.core.Event at 0x10c84dc90>,
 'to_initial': <transitions.core.Event at 0x10c84dad0>,
 'two': <transitions.core.Event at 0x10c84db10>}

In [11]: m.add_state('two')

In [12]: m.to_two()
[14/Jan/2016 16:39:32] INFO [transitions.core:131] Initiating transition from state initial to state two...
[14/Jan/2016 16:39:32] INFO [transitions.core:58] Exited state initial
[14/Jan/2016 16:39:32] INFO [transitions.core:51] Entered state two
Out[12]: True

In [13]: m.one()
---------------------------------------------------------------------------
MachineError                              Traceback (most recent call last)
<ipython-input-13-81b3745163c6> in <module>()
----> 1 m.one()

/Users/administrator/.virtualenvs/test/lib/python2.7/site-packages/transitions/core.pyc in trigger(self, *args, **kwargs)
    227                 logging.warning(msg)
    228             else:
--> 229                 raise MachineError(msg)
    230         event = EventData(self.machine.current_state, self, self.machine,
    231                           self.machine.model, args=args, kwargs=kwargs)

MachineError: "Can't trigger event one from state two!"
```

**Comment by tyarkoni** [comment]
I agree that this is the current behavior, but to me this feels more like a feature than a bug. It seems dangerous to treat the wildcard as a special directive to *always* send all states to a particular target, because that can have unpredictable effects if you forget you added the wildcard at some point in the past. The alternative approach is that, after you add new states, you just re-add the wildcard transition, which is a single extra line of code. But in general, I would not expect a state transition matrix to update dynamically in response to later state additions/changes without explicit modification. So unless there's a consensus that we should change this, I incline to leave it as-is (though I'd be happy to tweak the README to mention that this is the behavior).

**Comment by GertBurger** [comment]
Thanks for the quick response!

A notice in the README would be a good addition.
