### ISSUE TITLE
on_enter when initialzing machine

### ISSUE THREAD

**Issue by SteveAmor** [tyarkoni/transitions#71]
Given:
```python
>>> from transitions import Machine
>>> class Practise(object):
...     def on_enter_A(self): print("We've just entered state A!")
... 
>>> test = Practise()
```

Is there any reason why:
```python
>>> machine = Machine(model=test, states=['A', 'B', 'C'], initial='A')
```

Doesn't immediately return:
```python
"We've just entered state A!"
```

As it does when you enter state A subsequent times:
```python
>>> machine.add_transition('repeat', source='A', dest='A')
>>> test.repeat()
We've just entered state A!
True
```
Thanks.

**Comment by SteveAmor** [comment]
I think this is the same as #9 ?

**Comment by aleneum** [comment]
Hi @SteveAmor, 
yes and no. #9 is a about a 'null' initial state but you are talking about a defined state. Question here is: 

```python
m1 = Machine(practise, states=['A','B','C'], initial='A') # on_enter_A not called
m2 = Machine(practise, states=['A','B','C'])
m2.to_A() # on_enter called
```
Should `m1` and `m2` be expected to behave the same? My first impression is: yes they should. Let's see what others think.

Best regards,
Alex

**Comment by wtgee** [comment]
I go back and forth on this. Certainly it was the behavior I was expecting the first time around. It's complicated a bit by running a machine in some sort of event loop:

```python
# Machine
m1 = Machine(my_model, states=['A','B','C'], initial='A') # I don't want on_enter_A called here

# Do some other stuff

# Start machine
my_model.run() # I want on_enter_A called here
```

Since my machine is in an event loop, I do:

```python
# Machine
m1 = Machine(my_model, states=['A','B','C'], initial='C') # Or could be null initial state 

# Start machine
my_model.run() # run() calls .to_A()
```

Basically, I think many people won't view the machine creation and the "starting" of the machine as the same thing.

**Comment by SteveAmor** [comment]
I understand and think it is best to "create" the machine and then "start" the machine.

That is if your final command calls .to_C()  ;-)

**Comment by aleneum** [comment]
> Basically, I think many people won't view the machine creation and the "starting" of the machine as the same thing.

good point. I can see where this is a feature rather than a bug :). So `initial` just defines which transitions are valid from the start and in which state the machine 'wakes up' so to speak. In this case I'd would suggest:
```python
m1 = Machine(practise, states=['A','B','C']) # initialised in 'null' state
... 
m1.to_A() # calls on_enter
```
if `on_enter` executes code which _always_ has to be performed before state A. This workaround just requires one additional line to achieve @SteveAmor's expected result. Nevertheless, this 'special' behaviour for init states is worth mentioning in the documentation, isn't it?

**Comment by SteveAmor** [comment]
I just realised, the machine is already running as it alllows you to transition to other states.  So it's not like you're setting it up and then "starting" it.

I agree that the solution is documentation.

**Comment by aleneum** [comment]
I was wondering about a 'why' this specific behaviour is intended since the 'why' may be useful for the docs. I came up with the following:

I guess the crucial point is that the machine is started _within_ the state and not before it. In some scenarios `on_enter` might be undesired behaviour since the transition _into_ the initial state is undefined in the current implementation (as discussed in #9).

Let us say we have a system with an `idle` state which receives information about the last successful task via transitions and therefore via `on_enter`:

```python
class Model:
    def on_enter_idle(self, result):
        self.process(result)

states = ['idle', 'taskA',..., 'taskN']
transitions = [
    ['finished', '*', 'idle'],
    ['doA', 'idle', 'taskA'],
    ...
    ['doN', 'idle', 'taskN']
]

m = Machine(Model(), states=states, transitions=transitions, initial='idle')
m.doA()
...
m.finish(result)
```
In this case we do not want `on_enter` to be called if we set `initial="idle"` since there is no previously finished task and result to be processed.

Of course this problem can be solved by design with a dedicated initial state:
```python
states = ['initial', 'idle', ...]
# either
transitions = ['doA', ['initial', 'idle'], 'taskA']
# or 
class Model:
    def on_enter_initial(self):
        self.machine.to_idle()
```
 or by certain measurements in `on_enter` like:
```python
def on_enter_idle(result=None):
  if result:
    self.process(result)
```
However, the caused overhead to _prevent_ execution of `on_enter` is significantly larger than to _execute_ it by calling `to_A()`.

Does this sound reasonable?

**Comment by tyarkoni** [comment]
To be honest, I don't think I considered this issue at all when I wrote the original code, so I'm not going to give an elaborate justification for doing it one way versus the other. That said, it does feel more natural to me to *not* trigger callbacks at instantiation. And I agree with @aleneum's reasoning: it's trivial to make sure a function gets called at initialization (worse case, you just call it manually), but less trivial to prevent an unwanted callback from firing when it shouldn't. So let's leave the code as-is. I'll add a small note to the docs to this effect.
