### ISSUE TITLE
Graph Mixin Support

### ISSUE THREAD

**Issue by wtgee** [tyarkoni/transitions#75]
I've added in the graph as a mixin as per @aleneum's suggestion. Please take a look and see if it works for you.

Adds a `graph` attribute to the machine which will auto-track the changes and apply the style attribute from the `MachineGraphSupport` instance according to the `styles_attribute` defined in the base `AGraph` class. Currently has three styles: `default`, `active`, `passive`

Example notebook [here](https://github.com/tyarkoni/transitions/blob/dev-graph/examples/Graph%20MIxin%20Demo.ipynb)

Feel free to iterate on the dev-graph branch.

**Comment by wtgee** [comment]
@svdgraaf can you give your input too since you original developed the graphs. Thanks!

**Comment by svdgraaf** [comment]
I like it! :D

**Comment by aleneum** [comment]
I branched `dev-graph` into `dev-refactor` and pushed some code around. Every extension now has its own file in transitions/extensions. Mixing happens in `factory.py`.

Changes include:
* MachineFactory -- A user can call MachineFactory.get_predefined(graph=True/False, locked=True/False, nested=True/False) to get the right class. At first I tried dynamic creation of classes with custom names but pickle does not support this
* GraphSupport
  - Some examples in the ReadMe use the model parameter without keyword. That's why I had to push `title` it to the **kwargs. Otherwise GraphSupport treats the model like a title.
  - Pickling: I added `_get_state_` and `_set_state_`since `AGraph` contains a `SwigPyObject` which cannot be pickled that easy. Pickling for now destroys the 'previous' markup since the state is not explicitly (re)stored.
 - NestedMachines: I added support for NestedStates into `TransitionGraphSupport`. It just checks if a dest state has children or not.
* Notebooks now work without the need of installing transitions and I also added an example for nested graphs.

**Comment by tyarkoni** [comment]
Looks great to me! Will merge as soon as you submit a PR.

**Comment by aleneum** [comment]
i fixed two bugs. Tests fail at the moment because travis has some ubuntu package fetching issues. Looks like someone delete essential files from http://us-central1.gce.archive.ubuntu.com m).

**Comment by wtgee** [comment]
Closed with #79
